### ISSUE TITLE
Show appropriate server errors on screens

### ISSUE THREAD

**Issue by adil1508** [draftt/draftt#121]
Go through all of the screens and make sure that the appropriate errors from server (400 for example) are displayed on the screen. 

It's not showing on Account Activation screen currently,  which prompted this issue

**Comment by aarajh** [comment]
@adil1508 We can either do this in the backend or have a file in frontend with all the error and codes and then import from there lookup in that file

**Comment by adil1508** [comment]
Yeah that too. 

Plus i need to write a helper component that returns a list of properly formatted error messages that we get from the Server.
It will:
1. make it easy to re-use
2. make things look similar
3. handle the case where the errors returned by the Server do not correspond to the keys if the inputs in the Formik forms

**Comment by adil1508** [comment]
Also, me needs to look at some nice modal library we can use. doesn't look like it's going to be too much effort to add that in rn rather than later

https://github.com/react-native-community/react-native-modal

**Comment by aarajh** [comment]
@adil1508 make a ticket for it?

**Comment by adil1508** [comment]
i'll do it as part of this
