### ISSUE TITLE
[FE] Fix fields hidden behind keyboard

### ISSUE THREAD

**Issue by adil1508** [draftt/draftt#72]
The form fields hide behind the keyboard when it comes up. Need to figure out why that is and deal with it permanently.

If nothing comes up, switch up the screens. No need to spend a lot of time on it.

**Comment by adil1508** [comment]
this will only be a problem for shorter screens

**Comment by aarajh** [comment]
@adil1508 Is this still going to be an issue or can we close this?

**Comment by adil1508** [comment]
I think we can close this for now. 

I'll make a note in Notion so that we eventually come back to take a looksy

@aarajh
